site_name: Data Hopper

theme:
  name: 'material'
  palette: 


    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night 
        name: Dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode

  font:
    code: Nunito

nav:
  - Data Hopper: 'index.md'
  - User Guide:
      - Manager: 'modules/manager.md'
      - Summary: 'modules/summary.md'
  - Get Help: 'help-data-hopper.md'
  - Development - Contribuiting: 'contribuiting.md'
  - Release Notes: 'release-notes.md'
